# Appointment Reminder Configuration

# Twilio Settings
calling:
  # Retry attempts for failed calls
  max_retries: 3
  # Seconds to wait between retries
  retry_delay_seconds: 300
  # Call duration timeout in seconds
  call_timeout_seconds: 60
  # Enable voicemail detection
  detect_voicemail: true
  # Status callback URL for real-time updates (optional, requires ngrok or server)
  # Example: "https://abc123.ngrok.io/status"
  status_callback_url: null

# Excel File Settings
data:
  # Required column names
  required_columns:
    - name
    - phone_number
    - email
    - appointment_date
  # Date format in Excel files (e.g., "%Y-%m-%d %H:%M")
  date_format: "%Y-%m-%d %H:%M"
  # Default date format if cannot parse
  fallback_date_format: "%m/%d/%Y %H:%M"

# Logging Settings
logging:
  # Log file path
  log_file: "logs/appointment_reminder.log"
  # Batch call results log file
  batch_log_file: "logs/batch_call_results.csv"
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_level: "INFO"
  # Maximum log file size in bytes before rotation
  max_log_size: 10485760  # 10 MB
  # Number of backup log files to keep
  backup_count: 5

# Message Content
message:
  # Text-to-speech message template
  # {name}, {appointment_date}, {appointment_time}, {location}, {location_text} will be replaced
  # {location_text} includes " at [location]" if location exists, otherwise empty string
  # {location} is the raw location value (empty string if not provided)
  message_template: "Hello {name}, this is Jerry from the AARP TaxAide program calling with a reminder that you have an appointment scheduled for {appointment_date} at {appointment_time}{location_text}. If you need to reschedule, please contact us. Thank you."

